title : Documentation for Next-L Enju
author :
  name : Project Next-L
  url  : https://www.next-l.jp
  twitter : ProjectNextL
  feedburner : false

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
    - includedir=../_includes
    - imagesdir=../assets/images
safe: true

theme: just-the-docs
logo: "/assets/images/logo.png"
nav_external_links:
  - title: "Project Next-L公式サイト"
    url: "https://www.next-l.jp"
  - title: "GitHub (next-l/enju_leaf)"
    url: "https://github.com/next-l/enju_leaf"
footer_content: '&copy; 2007 Project Next-L'
search_enabled: false