---
:layout: page 
:group: enju_webapi
:page-layout: page
:title_short: 第2章 検索結果詳細を取得
:title: 第2章 検索結果詳細を取得 - Next-L Enju Web APIマニュアル
:version: 1.4
---

:toc: macro
:sectnums:

toc::[]

== 検索結果詳細を取得する

Enju は資料の検索結果詳細を好みのフォーマットで取得する機能があります。

=== TSVを取得する

==== TSV取得方法

. 書き出しをしたい検索結果詳細画面を表示させます。
. 検索結果詳細アドレス欄のURLの後ろに.txtを追加します。
+
....
例
（変更前）：http://localhost:8080/manifestations/5
（変更後）：http://localhost:8080/manifestations/5.txt
....
+
にします
+
※ 検索結果詳細画面の右メニューの[TSV]リンクをクリックした先のURLと同様です(詳細：link:enju_user_1.html#section1-9-3[利用者マニュアル「1-9-3 TSV 形式で書き出し」]）。
+
. この検索結果詳細画面がTSV形式で表示されます。

==== 書誌と所蔵のTSVの例

....
manifestation_id	original_title	title_transcription	creator	contributor	publisher	pub_date	statement_of_responsibility	manifestation_price	manifestation_created_at	manifestation_updated_at	manifestation_identifier	access_address	description	note	extent	dimensions	carrier_type	edition	edition_string	volume_number	volume_number_string	issue_number	issue_number_string	serial_number	isbn	issn	jpno	doi	iss_itemno	lccn	subject:unknown	subject:ndlsh	subject:bsh	subject:lcsh	classification:ndc9	classification:ddc	classification:ndc8	classification:ndc10	item_id	item_identifier	call_number	item_note	item_price	acquired_at	accepted_at	bookstore	budget_type	total_checkouts	circulation_status	shelf	library	item_created_at	item_updated_at
3	パーフェクトRuby on Rails	パーフェクト ルビー オン レイルズ	すがわら, まさのり, 1982-//前島, 真一//近藤, 宇智朗		技術評論社	2014-07	すがわらまさのり, 前島真一, 近藤宇智朗, 橋立友宏 著	2880	2018-01-08 21:27:20 +0900	2018-01-08 21:27:57 +0900	http://iss.ndl.go.jp/books/R100000002-I025470389-00				431p	23cm	volume								9784774165165		22426486		R100000002-I025470389-00		""	ウェブアプリケーション	""	""	547.483	""	""	""	3	001003	547|ス	""						0	Available On Shelf	first_shelf	yours	2018-01-08 21:27:57 +0900	2018-01-08 21:27:57 +0900
....

==== 書誌と所蔵のTSVの項目

link:enju_webapi_1.html#bib_tsv_export[書誌と所蔵のTSVの項目（1-1-3節参照）]を参照してください。

=== RDF/XML形式のデータを取得する

==== RDF/XML形式のデータ取得方法

. 書き出しをしたい検索結果詳細画面を表示させます。
. 検索結果詳細アドレス欄のURLの後ろに.rdfを追加します。
+
....
例
（変更前）：http://localhost:8080/manifestations/2
（変更後）：http://localhost:8080/manifestations/2.rdf
....
+
にします
+
※ 検索結果詳細画面の右メニューの[RDF/XML]リンクをクリックした先のURLと同様です(詳細：link:enju_user_1.html#section1-9-1[利用者マニュアル「1-9-1 RDF/XML 形式で書き出し」]）。
+
. この検索結果詳細画面がRDF/XML形式で表示されます。

==== 書誌のRDF/XML形式のデータの例

....
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns="http://purl.org/rss/1.0/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcndl="http://ndl.go.jp/dcndl/terms/" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:prism="http://prismstandard.org/namespaces/basic/2.0/" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
<title>Ruby on Rails入門 : 優しいRailsの育て方</title>
<link>http://localhost:8080/manifestations/1</link>
<description>秀和システム; 2006-08</description>
</rdf:RDF>
....

include::enju_webapi_toc.adoc[]
