---
layout: page
group: enju_webapi
page-layout: page
title_short: 第3章 書誌情報をまとめて取得する (OAI-PMH)
title: 第3章 書誌情報をまとめて取得する (OAI-PMH) - Next-L Enju Web APIマニュアル
version: 1.4
---

:toc: macro

toc::[]

== 書誌情報をまとめて取得する (OAI-PMH)

Enjuは資料の書誌情報全体をまとめて取得するOAI-PMIハーベスティングに対応しています。

OAI-PMHの詳細な仕様は https://www.nii.ac.jp/irp/archive/translation/oai-pmh2.0/[OAI-PMH2.0日本語訳（https://www.nii.ac.jp/irp/archive/translation/oai-pmh2.0/）] などをご覧ください。

=== アクセス先（ベースURL）

OAI-PMHのアクセス先は以下のように、Enjuの稼働するサーバアドレスに `/oai` をつけたものになります。

----
http://localhost:8080/oai?verb={_Verb_}
----

=== 取得できるメタデータ形式

EnjuがOAI-PMHで提供するメタデータ形式は Dublin Core, junii2, DCNDL の3種類に対応しています。
それぞれメタデータ名称として oai_dc, junii2, dcndl を指定してください。

=== サーバ情報を取得する (Identify)

サーバ情報を取得するには Identify リクエストを送ります。

----
http://localhost:8080/oai?verb=Identify
----

=== 対応メタデータ形式を確認する (ListMetadataFormats)

OAI-PMHで提供可能なメタデータ形式の一覧を取得するには ListMetadataFormats リクエストを送ります。

----
http://localhost:8080/oai?verb=ListMetadataFormats
----

=== 書誌情報を取得する (ListRecords)

書誌情報レコードを取得するには ListRecords リクエストを送ります。
取得されるメタデータ形式として、`metadataPrefix` パラメータで指定します。

DCNDLの場合:

----
http://localhost:8080/oai?verb=ListRecords&metadataPrefix=dcndl
----

junii2の場合:

----
http://localhost:8080/oai?verb=ListRecords&metadataPrefix=junii2
----

一度に取得できるレコード件数は100件までです。
必要に応じて、``resumptionToken``パラメータを使って複数回リクエストを送ることにより、Enju内の書誌情報レコードをすべて取得するハーベスティングを実現できます。

そのほか、`from`, `until` パラメータを使って、更新日付を限定したレコード取得も可能です。

更新日付によって限定したレコードの取得の例（2016年4月1日から2016年6月30日まで、DCNDL形式での取得）:

----
http://localhost:8080/oai?verb=ListRecords&metadataPrefix=dcndl&from=2016-04-01&until=2016-06-30
----

[[resourcesync]]
== 書誌情報をまとめて取得する (ResourceSync)

EnjuはOAI-PMHのほか、ResourceSyncによる書誌情報のまとめて取得にも対応しています。

[NOTE]
====
EnjuにおけるResourceSync APIの利用は、Enju管理者が出力設定を有効にしている場合のみ利用可能です。ResourceSyncの設定方法は xref:enju_setup_7.adoc#resourcesync-setup[ResourceSyncの設定方法（初期設定マニュアル）] をご覧ください。
====

ResourceSyncの仕様は https://www.openarchives.org/rs/1.1/resourcesync[ResourceSync Framework Specification] をご覧ください。

=== 書誌情報を取得する

ResourceSyncで書誌情報を取得するには、全体の書誌情報提供機能の一覧 (capability list) と書誌情報リスト
 (resource list) の2種類のURLにアクセスする必要があります。

全体の書誌情報提供機能の一覧 (capability list) のURLは以下のようになります。

http://localhost:8080/capabilitylist.xml

書誌情報リスト (resource list) のURLは以下のようになります。

http://localhost:8080/resourcelist_index.xml


include::enju_webapi_toc.adoc[]
