name: build a doc files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: asciidoctor-ghpages
      uses: manoelcampos/asciidoctor-ghpages-action@v2.3.0
